### ISSUE TITLE
Autocomplete Pub Packages is not working as expected.

### ISSUE THREAD

**Issue by ericklhe** [marius-h/flutter_enhancement_suite#15]
**Describe the bug**
When trying to add different libraries (cloud_firestore, firebase_auth, etc...) the plugin does not return any hint.

I'm getting "No packages found" when I type firebase_auth, cloud_firestore, vector_math, etc...

**Comment by Solido** [comment]
It's working on my side, what's your version of the plugin ? 
does it fail with all packages or specific ones ?

**Comment by ericklhe** [comment]
@Solido I'm using v1.2. For example, if I want to search for the camera library, the plugin is only showing me camscan. I can't add any flutterfire plugin.

**Comment by marius-h** [comment]
I cannot reproduce this issue. The only explanation for your issue could be because of a weak internet connection or if you are offline.

![image](https://user-images.githubusercontent.com/29115214/64363099-0eed5600-d010-11e9-8bae-88ccf58787ba.png)

![image](https://user-images.githubusercontent.com/29115214/64363133-23c9e980-d010-11e9-9833-0d21bd6d68cd.png)
