### ISSUE TITLE
Intellij 2019.1.4 is stuck with 1.0

### ISSUE THREAD

**Issue by Solido** [marius-h/flutter_enhancement_suite#2]
Plugins manager says there's not update so I can't update to the last version.
Using the last version of IntelliJ, search says it's up to date.

Can't wait to see the full potential of this plugin

**Comment by marius-h** [comment]
This relates to issue #1. In IntelliJ 2019.2 they extracted the Java functionality to a separate plugin. When fixing the plugin to work with IntelliJ 2019.2, I built the plugin with version 2019.2 which causes the plugin to not work with older versions (I've already contacted JetBrains' support because of this issue). I'm now waiting for JetBrains to release the latest update (v1.1.3) which should fix that issue.
You can already download it [here](https://github.com/marius-h/flutter_enhancement_suite/releases/download/v1.1.3/FlutterEnhancementSuite-1.1.3.zip). I would appreciate it if you would report to me whether your problem has been solved.

Cheers
Marius

**Comment by Solido** [comment]
I did not have to use the DL link ! 
Coming back to my IDE it offered the update and it's now working.
I love it !

Also what's your twitter ? 
https://twitter.com/BlueAquilae/status/1159426454272335872
